apiVersion: apps/v1
kind: Deployment
metadata:
  name: formativa-users-deployment
  labels:
    app: formativa-users-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: formativa-users
  template:
    metadata:
      labels:
        app: formativa-users
    spec:
      containers:
      - name: formativa-users-container
        image: tallernetcore.azurecr.io/formativa-users-api:0.0.2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: formativa-users-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: formativa-users

